### ISSUE TITLE
Update ISTA penalties at every time step

### ISSUE THREAD

**Issue by jack-willturner** [jack-willturner/batchnorm-pruning#7]

**Comment by jack-willturner** [comment]
7fc0c0a541819f8bde6df887f135ac550ec6463e

**Comment by heerduo** [comment]
in main 94  ' ista = ((1/ i_w * i_h) * (k_w * k_h * c_next))' should be  ista = (1/( i_w * i_h) * (k_w * k_h * c_next)) ?  According to the paper 1/( i_w * i_h)
